### ISSUE TITLE
Issue for Big Sur

### ISSUE THREAD

**Issue by Luckeee** [elegracer/NetSpeedMonitor#8]
just like the image. Not in center

![123](https://user-images.githubusercontent.com/8073332/101976603-baf50680-3c81-11eb-9b16-3d7a0fcad859.png)

**Comment by elegracer** [comment]
Thank you for your feedback! Since I don't have a Big Sur environment, I cannot test it.

If you'd like to help me, please put `if #available(macOS 11, *) {}` here <https://github.com/elegracer/NetSpeedMonitor/blob/08752c5dcf4ec2b5be81c1a4dbd5e2a962d341d4/NetSpeedMonitor/AppDelegate.swift#L65>

So that it looks like this

```swift
            if #available(macOS 11, *) {
                paragraphStyle.maximumLineHeight = 10
                paragraphStyle.paragraphSpacing = -5 // modify this
                return [
                    NSAttributedString.Key.font : font,
                    NSAttributedString.Key.paragraphStyle: paragraphStyle
                ] as [NSAttributedString.Key : Any]
            } else {
                paragraphStyle.maximumLineHeight = 10
                paragraphStyle.paragraphSpacing = -5
                return [
                    NSAttributedString.Key.font : font,
                    NSAttributedString.Key.paragraphStyle: paragraphStyle
                ] as [NSAttributedString.Key : Any]
            }
```

And adjust the `if` branch to make it look nice, then take a merge request, and I will merge it.

**Comment by Luckeee** [comment]
I had modified the paragraphStyle.paragraphSpacing from -100 to 100 yesterday,but it did not work correct yet😂. It just act as zhe above image.

**Comment by elegracer** [comment]
I've updated my macOS to Big Sur and fixed this issue. Please check it there's any other problems.
